// src/modules/contracts/templates/contract.html.ts

export interface ContractViewModel {
  contract: any;
  client: any;
  parties?: any[];
  vas?: any[];
  oda?: any[];
  region?: any[];
  insurance?: any[];
  incentives?: any[];
  rateMatrix?: any[];
  volumetric_bases?: any[];
}

export function renderContractHTML(vm: ContractViewModel): string {
  const c = vm.contract || {};
  const cli = vm.client || {};
  const fmt = (v: any) => (v == null ? "" : String(v));

  const parties = (vm.parties ?? [])
    .map(
      (p: any) => `
        <tr>
          <td>${fmt(p.party_role)}</td>
          <td>${fmt(p.legal_name)}</td>
          <td>${fmt(p.city)}, ${fmt(p.state)}</td>
        </tr>`
    )
    .join("");

  const vasRows = (vm.vas ?? [])
    .map(
      (v: any) => `
        <tr>
          <td>${fmt(v.vas_code)}</td>
          <td>${fmt(v.calc_method)}</td>
          <td>${fmt(v.rate_per_kg)}</td>
          <td>${fmt(v.rate_per_cn)}</td>
          <td>${fmt(v.min_per_cn)}</td>
          <td>${fmt(v.max_per_cn)}</td>
        </tr>`
    )
    .join("");

  const odaRows = (vm.oda ?? [])
    .map(
      (o: any) => `
        <tr>
          <td>${fmt(o.oda_code)}</td>
          <td>${fmt(o.rate_per_kg)}</td>
          <td>${fmt(o.min_per_cn)}</td>
          <td>${fmt(o.notes)}</td>
        </tr>`
    )
    .join("");

  const rateRows = (vm.rateMatrix ?? [])
    .map(
      (r: any) => `
        <tr>
          <td>${fmt(r.origin_city)}</td>
          <td>${fmt(r.dest_city)}</td>
          <td>${fmt(r.cft_base)}</td>
          <td>${fmt(r.base_rate_rs)}</td>
          <td>${fmt(r.currency)}</td>
        </tr>`
    )
    .join("");

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Contract ${fmt(c.contract_code)}</title>
  <style>
    body { font-family: Arial, Helvetica, sans-serif; color:#111; }
    h1,h2 { margin: 0 0 8px 0; }
    small, .meta { color:#666; }
    table { width:100%; border-collapse: collapse; margin: 12px 0; }
    th, td { border:1px solid #ddd; padding:8px; font-size: 12px; vertical-align: top; }
    th { background:#f6f6f6; text-align: left; }
    .section { margin-top: 18px; }
  </style>
</head>
<body>
  <h1>Service Agreement</h1>
  <div class="meta">
    <div>Contract Code: <b>${fmt(c.contract_code)}</b></div>
    <div>Client: <b>${fmt(cli.client_name)}</b> (${fmt(cli.client_code)})</div>
    <div>Agreement Date: ${fmt(c.agreement_date)}</div>
    <div>Term: ${fmt(c.term_start)} → ${fmt(c.term_end)} (${fmt(
    c.term_months
  )} months)</div>
    <div>Settlement: ${fmt(c.settlement_frequency)} | GST: ${fmt(
    c.taxes_gst_pct
  )}%</div>
  </div>

  <div class="section">
    <h2>Parties</h2>
    <table>
      <thead><tr><th>Role</th><th>Legal Name</th><th>Location</th></tr></thead>
      <tbody>${parties || '<tr><td colspan="3"><i>None</i></td></tr>'}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>Rate Matrix</h2>
    <table>
      <thead><tr><th>Origin</th><th>Destination</th><th>CFT Base</th><th>Base Rate (₹)</th><th>Currency</th></tr></thead>
      <tbody>${rateRows || '<tr><td colspan="5"><i>None</i></td></tr>'}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>Value Added Services</h2>
    <table>
      <thead><tr><th>VAS</th><th>Method</th><th>₹/kg</th><th>₹/CN</th><th>Min</th><th>Max</th></tr></thead>
      <tbody>${vasRows || '<tr><td colspan="6"><i>None</i></td></tr>'}</tbody>
    </table>
  </div>

  <div class="section">
    <h2>ODA Charges</h2>
    <table>
      <thead><tr><th>ODA Code</th><th>₹/kg</th><th>Min ₹/CN</th><th>Notes</th></tr></thead>
      <tbody>${odaRows || '<tr><td colspan="4"><i>None</i></td></tr>'}</tbody>
    </table>
  </div>

  <div class="section">
    <small>Generated by Rapidero Logistics Contract Engine</small>
  </div>
</body>
</html>`;
}
